version: '3'
services:
  gps_serial:
    
    devices:
      - /dev/GPS:/dev/GPS
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

  ferex_serial:
    devices:
      - /dev/FAKEFEREX:/dev/FAKEFEREX
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

