version: '3'
services:
  gps_serial:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

  ferex_serial:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

