version: '3'
services:
  gps_serial:
    user: "1000:1000"  # Specify the user and group IDs
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

  ferex_serial:
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/var/log/supervisor

